name: Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create path
      run: mkdir -p my_files
    - name: Create file  
      run: echo "Hello, world!" >  hello.txt

    - name: Archive text file
      uses: actions/upload-artifact@v3
      with:
        name: my-hello-artifact
        path: hello.txt

  download:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - name: Download File
      uses: actions/download-artifact@v3
      with:
        name: my-hello-artifact
    - name: Read File
      run: cat hello.txt
   
